version: '3'
 
services:
  frontend:
    container_name: front-end-nlp-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: 'always'
    environment:
      - BACK_END_URL='http://docker.host.internal:3000/'
    ports:
      - 3001:3001
    depends_on:
      - backend
    networks:
      - nlp-app-network
 
  backend:
    container_name: back-end-nlp-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: 'always'
    ports:
      - 3000:3000
    volumes:
      - "nlp-app-db:/data/db"
    networks:
      - nlp-app-network
 
volumes:
  nlp-app-db:

networks:
  nlp-app-network: